# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='gmailid',
            field=models.CharField(blank=True, default=0, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Only Indian', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fbuser',
            name='fbid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
