# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170212_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('city', models.CharField(choices=[('1', 'C1'), ('2', 'C1'), ('3', 'C1')], default=0, max_length=5)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=2)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Only Indian', max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='fbUser',
        ),
    ]
