# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('D', 'Delivered'), ('E', 'Executing'), ('S', 'Submitted')], default=0, max_length=5, null=True)),
                ('test_id', models.CharField(choices=[('1', 't1'), ('2', 't2'), ('3', 't3')], default=0, max_length=6)),
            ],
        ),
    ]
