# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('Diabetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.MyUser'),
        ),
    ]
